name: Run Repo B Tests and Deploy

on:
  workflow_dispatch:

jobs:
  call-tests:
    uses: embroker/ams-qa/.github/workflows/ams-qa.yml@main
    with:
      environment: staging
      upload_testrail: true
    secrets: inherit
    permissions:
      contents: read
      actions: read