name: Run Repo B Tests and Deploy

on:
  workflow_dispatch:

jobs:
  call-tests:
    uses: luis-embroker/repo-b/.github/workflows/ams-qa.yml@main
    with:
      environment: staging
      upload_testrail: true