name: Run Repo B Tests and Deploy

on:
  workflow_dispatch:

jobs:
  call-tests:
    uses: luis-embroker/repo-b/.github/workflows/ams-qa.yml@main
    with:
      environment: staging
      upload_testrail: true

    secrets:
      CUCUMBER_CREDENTIALS_STAGING: ${{ secrets.CUCUMBER_CREDENTIALS_STAGING }}
      CUCUMBER_SF_JWT_KEY_STAGING: ${{ secrets.CUCUMBER_SF_JWT_KEY_STAGING }}

 